// Generated by gencpp from file ball_finder/BallLocation.msg
// DO NOT EDIT!


#ifndef BALL_FINDER_MESSAGE_BALLLOCATION_H
#define BALL_FINDER_MESSAGE_BALLLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ball_finder
{
template <class ContainerAllocator>
struct BallLocation_
{
  typedef BallLocation_<ContainerAllocator> Type;

  BallLocation_()
    : bearing(0)
    , distance(0)  {
    }
  BallLocation_(const ContainerAllocator& _alloc)
    : bearing(0)
    , distance(0)  {
  (void)_alloc;
    }



   typedef int32_t _bearing_type;
  _bearing_type bearing;

   typedef int32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::ball_finder::BallLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ball_finder::BallLocation_<ContainerAllocator> const> ConstPtr;

}; // struct BallLocation_

typedef ::ball_finder::BallLocation_<std::allocator<void> > BallLocation;

typedef boost::shared_ptr< ::ball_finder::BallLocation > BallLocationPtr;
typedef boost::shared_ptr< ::ball_finder::BallLocation const> BallLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ball_finder::BallLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ball_finder::BallLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ball_finder::BallLocation_<ContainerAllocator1> & lhs, const ::ball_finder::BallLocation_<ContainerAllocator2> & rhs)
{
  return lhs.bearing == rhs.bearing &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ball_finder::BallLocation_<ContainerAllocator1> & lhs, const ::ball_finder::BallLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ball_finder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ball_finder::BallLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_finder::BallLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_finder::BallLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_finder::BallLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_finder::BallLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_finder::BallLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ball_finder::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09f1160bffd7c7871c2baa2dd0283a30";
  }

  static const char* value(const ::ball_finder::BallLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09f1160bffd7c787ULL;
  static const uint64_t static_value2 = 0x1c2baa2dd0283a30ULL;
};

template<class ContainerAllocator>
struct DataType< ::ball_finder::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ball_finder/BallLocation";
  }

  static const char* value(const ::ball_finder::BallLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ball_finder::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bearing\n"
"int32 distance\n"
;
  }

  static const char* value(const ::ball_finder::BallLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ball_finder::BallLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearing);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ball_finder::BallLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ball_finder::BallLocation_<ContainerAllocator>& v)
  {
    s << indent << "bearing: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bearing);
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALL_FINDER_MESSAGE_BALLLOCATION_H
